import {Field} from "react-querybuilder";

export const ECGfields: Field[] = [
    { name: 'sinus', label: 'SINUS' },
    { name: 'rr_diff', label: 'RR_DIFF' },
    { name: 'hr', label: 'HR' },
    { name: 'pr_dur', label: 'PR_DUR' },
    { name: 'qrs_dur', label: 'QRS_DUR' },

    { name: 'st_amp_i', label: 'ST_AMP_I' },
    { name: 'st_amp_ii', label: 'ST_AMP_II' },
    { name: 'st_amp_iii', label: 'ST_AMP_III' },
    { name: 'st_amp_avr', label: 'ST_AMP_aVR' },
    { name: 'st_amp_avl', label: 'ST_AMP_aVL' },
    { name: 'st_amp_avf', label: 'ST_AMP_aVF' },
    { name: 'st_amp_v1', label: 'ST_AMP_V1' },
    { name: 'st_amp_v2', label: 'ST_AMP_V2' },
    { name: 'st_amp_v3', label: 'ST_AMP_V3' },
    { name: 'st_amp_v4', label: 'ST_AMP_V4' },
    { name: 'st_amp_v5', label: 'ST_AMP_V5' },
    { name: 'st_amp_v6', label: 'ST_AMP_V6' },

    { name: 'prwp', label: 'PRWP' },

    { name: 'q_dur_i', label: 'Q_DUR_I' },
    { name: 'q_dur_ii', label: 'Q_DUR_II' },
    { name: 'q_dur_iii', label: 'Q_DUR_III' },
    { name: 'q_dur_avr', label: 'Q_DUR_aVR' },
    { name: 'q_dur_avl', label: 'Q_DUR_aVL' },
    { name: 'q_dur_avf', label: 'Q_DUR_aVF' },
    { name: 'q_dur_v1', label: 'Q_DUR_V1' },
    { name: 'q_dur_v2', label: 'Q_DUR_V2' },
    { name: 'q_dur_v3', label: 'Q_DUR_V3' },
    { name: 'q_dur_v4', label: 'Q_DUR_V4' },
    { name: 'q_dur_v5', label: 'Q_DUR_V5' },
    { name: 'q_dur_v6', label: 'Q_DUR_V6' },

    { name: 'q_amp_i', label: 'Q_AMP_I' },
    { name: 'q_amp_ii', label: 'Q_AMP_II' },
    { name: 'q_amp_iii', label: 'Q_AMP_III' },
    { name: 'q_amp_avr', label: 'Q_AMP_aVR' },
    { name: 'q_amp_avl', label: 'Q_AMP_aVL' },
    { name: 'q_amp_avf', label: 'Q_AMP_aVF' },
    { name: 'q_amp_v1', label: 'Q_AMP_V1' },
    { name: 'q_amp_v2', label: 'Q_AMP_V2' },
    { name: 'q_amp_v3', label: 'Q_AMP_V3' },
    { name: 'q_amp_v4', label: 'Q_AMP_V4' },
    { name: 'q_amp_v5', label: 'Q_AMP_V5' },
    { name: 'q_amp_v6', label: 'Q_AMP_V6' },

    {name: 'p_dur_i', label: 'P_DUR_I'},
    { name: 'p_dur_ii', label: 'P_DUR_II' },
    {name: 'p_dur_iii', label: 'P_DUR_III'},
    {name: 'p_dur_avr', label: 'P_DUR_aVR'},
    {name: 'p_dur_avl', label: 'P_DUR_aVL'},
    {name: 'p_dur_avf', label: 'P_DUR_aVF'},
    {name: 'p_dur_v1', label: 'P_DUR_V1'},
    {name: 'p_dur_v2', label: 'P_DUR_V2'},
    {name: 'p_dur_v3', label: 'P_DUR_V3'},
    {name: 'p_dur_v4', label: 'P_DUR_V4'},
    {name: 'p_dur_v5', label: 'P_DUR_V5'},
    {name: 'p_dur_v6', label: 'P_DUR_V6'},

    { name: 'p_amp_i', label: 'P_AMP_I' },
    { name: 'p_amp_ii', label: 'P_AMP_II' },
    { name: 'p_amp_iii', label: 'P_AMP_III' },
    { name: 'p_amp_avr', label: 'P_AMP_aVR' },
    { name: 'p_amp_avl', label: 'P_AMP_aVL' },
    { name: 'p_amp_avf', label: 'P_AMP_aVF' },
    { name: 'p_amp_v1', label: 'P_AMP_V1' },
    { name: 'p_amp_v2', label: 'P_AMP_V2' },
    { name: 'p_amp_v3', label: 'P_AMP_V3' },
    { name: 'p_amp_v4', label: 'P_AMP_V4' },
    { name: 'p_amp_v5', label: 'P_AMP_V5' },
    { name: 'p_amp_v6', label: 'P_AMP_V6' },

    { name: 'age', label: 'AGE' },
    { name: 'male', label: 'MALE' },

    {name: 'r_amp_i', label: 'R_AMP_I'},
    {name: 'r_amp_ii', label: 'R_AMP_II'},
    {name: 'r_amp_iii', label: 'R_AMP_III'},
    {name: 'r_amp_avr', label: 'R_AMP_aVR'},
    { name: 'r_amp_avl', label: 'R_AMP_aVL' },
    { name: 'r_amp_avf', label: 'R_AMP_aVF' },
    { name: 'r_amp_v1', label: 'R_AMP_V1' },
    { name: 'r_amp_v2', label: 'R_AMP_V2' },
    { name: 'r_amp_v3', label: 'R_AMP_V3' },
    { name: 'r_amp_v4', label: 'R_AMP_V4' },
    { name: 'r_amp_v5', label: 'R_AMP_V5' },
    { name: 'r_amp_v6', label: 'R_AMP_V6' },

    {name: 's_amp_i', label: 'S_AMP_I'},
    {name: 's_amp_ii', label: 'S_AMP_II'},
    {name: 's_amp_iii', label: 'S_AMP_III'},
    {name: 's_amp_avr', label: 'S_AMP_aVR'},
    {name: 's_amp_avl', label: 'S_AMP_aVL'},
    {name: 's_amp_avf', label: 'S_AMP_aVF'},
    {name: 's_amp_v1', label: 'S_AMP_V1' },
    {name: 's_amp_v2', label: 'S_AMP_V2'},
    {name: 's_amp_v3', label: 'S_AMP_V3' },
    {name: 's_amp_v4', label: 'S_AMP_V4' },
    {name: 's_amp_v5', label: 'S_AMP_V5' },
    {name: 's_amp_v6', label: 'S_AMP_V6' },

    {name: 'rs_ratio_i', label: 'RS_RATIO_I' },
    {name: 'rs_ratio_ii', label: 'RS_RATIO_II'},
    {name: 'rs_ratio_iii', label: 'RS_RATIO_III'},
    {name: 'rs_ratio_avr', label: 'RS_RATIO_aVR'},
    {name: 'rs_ratio_avl', label: 'RS_RATIO_aVL'},
    {name: 'rs_ratio_avf', label: 'RS_RATIO_aVF'},
    { name: 'rs_ratio_v1', label: 'RS_RATIO_V1' },
    { name: 'rs_ratio_v2', label: 'RS_RATIO_V2' },
    { name: 'rs_ratio_v3', label: 'RS_RATIO_V3' },
    { name: 'rs_ratio_v4', label: 'RS_RATIO_V4' },
    { name: 'rs_ratio_v5', label: 'RS_RATIO_V5' },
    { name: 'rs_ratio_v6', label: 'RS_RATIO_V6' },

    { name: 't_amp_i', label: 'T_AMP_I' },
    { name: 't_amp_ii', label: 'T_AMP_II' },
    { name: 't_amp_iii', label: 'T_AMP_III' },
    { name: 't_amp_avr', label: 'T_AMP_aVR' },
    { name: 't_amp_avl', label: 'T_AMP_aVL' },
    { name: 't_amp_avf', label: 'T_AMP_aVF' },
    { name: 't_amp_v1', label: 'T_AMP_V1' },
    { name: 't_amp_v2', label: 'T_AMP_V2' },
    { name: 't_amp_v3', label: 'T_AMP_V3' },
    { name: 't_amp_v4', label: 'T_AMP_V4' },
    { name: 't_amp_v5', label: 'T_AMP_V5' },
    { name: 't_amp_v6', label: 'T_AMP_V6' },

    { name: 'qrs_sum_i', label: 'QRS_SUM_I' },
    { name: 'qrs_sum_ii', label: 'QRS_SUM_II' },
    { name: 'qrs_sum_iii', label: 'QRS_SUM_III' },
    { name: 'qrs_sum_avr', label: 'QRS_SUM_aVR' },
    { name: 'qrs_sum_avl', label: 'QRS_SUM_aVL' },
    { name: 'qrs_sum_avf', label: 'QRS_SUM_aVF' },
    { name: 'qrs_sum_avf', label: 'QRS_SUM_aVF' },
    { name: 'qrs_sum_v1', label: 'QRS_SUM_V1' },
    { name: 'qrs_sum_v2', label: 'QRS_SUM_V2' },
    { name: 'qrs_sum_v3', label: 'QRS_SUM_V3' },
    { name: 'qrs_sum_v4', label: 'QRS_SUM_V4' },
    { name: 'qrs_sum_v5', label: 'QRS_SUM_V5' },
    { name: 'qrs_sum_v6', label: 'QRS_SUM_V6' }
];